<?php

namespace ndtan;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\Group;

#[Group('integration')]
final class DriverTest extends TestCase
{
    public function testMysql(): void
    {
        $this->checkDriver('MYSQL', 'root');
    }

    public function testPostgres(): void
    {
        $this->checkDriver('PGSQL', 'postgres');
    }

    private function checkDriver(string $driver, string $user): void
    {
        $dsn = getenv('DBF_TEST_' . $driver);
        if (!$dsn) $this->markTestSkipped('Set DBF_TEST_' . $driver . ' for database integration tests.');
        $db = new DBF(['dsn' => $dsn, 'username' => $user, 'password' => 'dbf_test']);
        $table = 'dbf_test_' . bin2hex(random_bytes(6));
        $identity = $driver === 'MYSQL' ? 'INTEGER PRIMARY KEY AUTO_INCREMENT' : 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        $json = $driver === 'MYSQL' ? 'JSON' : 'JSONB';
        $db->execute("CREATE TABLE $table (id $identity, name VARCHAR(100) UNIQUE NOT NULL, data $json, score INTEGER)");
        try {
            $ids = $db->table($table)->insertMany([['name' => 'one'], ['name' => 'two']]);
            $this->assertCount(2, $ids);
            $this->assertGreaterThan($ids[0], $ids[1]);
            $db->table($table)->upsert(['name' => 'one', 'score' => 2], ['name'], ['score']);
            $this->assertSame(2, (int)$db->table($table)->where('name', '=', 'one')->first()['score']);
            $db->table($table)->where('name', '=', 'one')->update(['data' => '{"profile":{"name":"Old"},"score":1}']);
            $db->table($table)->where('name', '=', 'one')->jsonSet('data', ['profile.name' => 'New', 'score' => 9]);
            $row = $db->table($table)->whereJson('data->profile->name', '=', 'New')->first();
            $this->assertSame(9, json_decode($row['data'], true)['score']);
            $this->assertTrue($db->hasUniqueConstraint($table, ['name']));
            $this->assertTrue($db->hasUniqueConstraint($table, ['id']));
            $db->tx(function (DBF $tx) use ($table): void {
                $this->assertCount(1, $tx->table($table)->where('name', '=', 'one')->forUpdate()->get());
                $tx->tx(fn(DBF $nested) => $nested->table($table)->where('name', '=', 'one')->update(['score' => 3]));
            });
            $this->assertSame(2, $db->table($table)->count());
            $this->assertSame(1, count($db->table($table)->timeout(1000)->limit(1)->get()));
        } finally {
            $db->execute("DROP TABLE $table");
        }
    }
}
