name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
    # Cho phép 8.4 “được lỗi” tạm thời (nếu environment của 8.4 chưa stable)
    continue-on-error: ${{ matrix.php == '8.4' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, sqlite3, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Show PHP info
        run: |
          php -v
          php -m

      - name: Validate composer.json
        run: composer validate --no-interaction

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Dump autoload (optimize)
        run: composer dump-autoload -o

      - name: Run PHPUnit
        run: vendor/bin/phpunit --display-deprecations -v
